name: "Terraform Plan & Prisma Cloud Code Security"

# Trigger when a pull request is received
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform-plan-prisma-bridgecrew:
    name: "Terraform + BridgeCrew/Prisma Scan"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      # Checkout the code
      # Marketplace: https://github.com/marketplace/actions/checkout
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0
        

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: "Run - Terraform Init"
        run: terraform init -input=false

      # The id value is used for reference in the comment step via "steps.plan.outputs.stdout"
      # Note: Color is disabled to prevent messy characters from appearing in the pull request comment
      - name: "Run - Terraform Plan"
        id: plan
        run: terraform plan -input=false -no-color
      
      - name: Run Prisma Code Security
        id: Bridgecrew
        uses: bridgecrewio/bridgecrew-action@master
        env:
          PRISMA_API_URL: https://api2.prismacloud.io
        with:
          api-key: ${{ secrets.BRIDGECREW_API_KEY }}
          directory: ./
